### ISSUE TITLE
Outputting 1.000000 instead of 1

### ISSUE THREAD

**Issue by u-ndefine** [BigZaphod/Taxi#4]
Here is [the link](https://tio.run/##fZBBDoIwEEX3nmIOYEhwydINOyXRC4wwtBNrS9oh6OlriUSBEBdNfv7v9P2O4JNjzIEDDMjCVgEKXAR9rdk0cOof5J1x6pXtSgfiNrMCBgoCeTqGWtnDwTbgWekkf@YyHlW2q7i@9x0gdBgCWUUelBtbJNJVExzxRqbloMl/G0jy19mswcRdVVjL/@gRUbl099y2XNOcPLMLsM6LXn1xen7WNe0YSvSoFhOb@/kMx/gG) if you want to try it out yourself.
It outputs 1.000000 instead of 1. Is it intentional?

**Comment by DennisMitchell** [comment]
[JosiahRyanW wrote](https://chat.stackexchange.com/transcript/message/47005930#47005930):

> I just investigated for myself, and the problem is that the source code uses a function called to_string, which (at this point in time) has the same name as another C++ function. The "fix" for this would simply be to call it by a different name wherever it's used.

The easiest way to fix this is to compile Taxi as C++03, which avoids the name clash. @u-ndefine TIO does this now, so your permalink prints 1.
